document.addEventListener("DOMContentLoaded",function(){const wishlistMenu=document.getElementById("WishlistMenu");const wishlistIcon=wishlistMenu?.querySelector(".wishlist-icon");const wishlistProducts=wishlistMenu?.querySelector("#WishlistProducts");const wishlistCount=wishlistMenu?.querySelector(".wishlist-count");const overlay=document.getElementById("Overlay");const wishlistPage=document.getElementById("wishlistPage");let scrollYBeforeOpen=0;const wishlist={items:JSON.parse(localStorage.getItem("wishlistItems"))||[],save(){localStorage.setItem("wishlistItems",JSON.stringify(this.items));this.updateAllUI();window.dispatchEvent(new CustomEvent("wishlistUpdated"))},addItem(item){if(!this.items.find((i)=>i.id===item.id)){this.items.push(item);this.save();this.openMenu()}},removeItem(id){this.items=this.items.filter((i)=>i.id!==id);this.save()},clearAll(){if(this.items.length===0)return;if(confirm("Are you sure you want to clear your entire wishlist?")){this.items=[];this.save()}},openMenu(){if(wishlistProducts){scrollYBeforeOpen=window.scrollY;wishlistProducts.classList.add("active");overlay?.classList.add("active");document.body.style.position='fixed';document.body.style.width='100%';document.body.style.top=`-${scrollYBeforeOpen}px`}},toggleItem(item){const exists=this.items.find((i)=>i.id===item.id);exists?this.removeItem(item.id):this.addItem(item)},updateAllUI(){this.updateMenuUI();this.updatePageUI();this.updateProductButtons()},updateMenuUI(){if(wishlistCount)wishlistCount.textContent=this.items.length;const listContainer=wishlistMenu?.querySelector(".wishlist-items");const emptyState=wishlistMenu?.querySelector(".empty-state");if(listContainer&&emptyState){listContainer.innerHTML="";if(this.items.length===0){emptyState.classList.remove("hidden");listContainer.classList.add("hidden")}else{emptyState.classList.add("hidden");listContainer.classList.remove("hidden");this.items.forEach((item)=>{const div=document.createElement("div");div.className="wishlist-item";div.innerHTML=`
                            <img src="${item.image}" class="wishlist-thumb" alt="${item.title}" />
                            <div class="wishlist-info">
                                <p class="wishlist-title">${item.title}</p>
                                <div class="wishlist-actions">
                                    <a href="${item.url}" title="View Product"><i class="bi bi-box-arrow-up-right"></i></a>
                                    <button class="remove-wishlist-item" data-id="${item.id}" title="Remove">
                                        <i class="bi bi-x"></i>
                                    </button>
                                </div>
                            </div>
                        `;listContainer.appendChild(div)})}}},updatePageUI(){const container=document.querySelector(".wishlist-items-container");const emptyPageState=document.querySelector(".wishlist-page .empty-state");if(container){container.innerHTML="";if(this.items.length===0){if(emptyPageState){emptyPageState.classList.remove("hidden");container.classList.add("hidden")}else{container.innerHTML=`
                            <div class="empty-state">
                                <i class="bi bi-heartbreak"></i>
                                <p>Your wishlist is currently empty</p>
                            </div>
                        `}}else{if(emptyPageState){emptyPageState.classList.add("hidden");container.classList.remove("hidden")}
this.items.forEach((item)=>{const div=document.createElement("div");div.className="wishlist-page-item";div.innerHTML=`
                            <img src="${item.image}" class="wishlist-page-thumb"/>
                            <div class="wishlist-page-info">
                                <h2>${item.title}</h2>
                                <div class="wishlist-page-actions">
                                    <a href="${item.url}" class="view-btn" title="View Product">
                                        <i class="bi bi-box-arrow-up-right"></i> View Product
                                    </a>
                                    <button class="remove-btn" data-id="${item.id}" title="Remove">
                                        <i class="bi bi-x-circle"></i> Remove
                                    </button>
                                </div>
                            </div>
                        `;container.appendChild(div)})}}},updateProductButtons(){document.querySelectorAll(".Layra-add-to-wishlist").forEach((btn)=>{const id=btn.getAttribute("data-id");const icon=btn.querySelector("i");const isInWishlist=this.items.some((i)=>i.id===id);btn.classList.toggle("added",isInWishlist);if(icon){icon.className=isInWishlist?"bi bi-heart-fill text-red":"bi bi-heart"}})},};window.wishlist=wishlist;wishlist.updateAllUI();window.addEventListener("storage",function(event){if(event.key==="wishlistItems"){console.log("[Wishlist Sync] Detected change from another tab → reloading");wishlist.items=JSON.parse(localStorage.getItem("wishlistItems"))||[];wishlist.updateAllUI()}});document.addEventListener("click",function(e){const btn=e.target.closest(".Layra-add-to-wishlist");if(btn){e.preventDefault();const id=btn.getAttribute("data-id");const title=btn.getAttribute("data-title");const url=btn.getAttribute("data-post-url")||btn.href;const container=btn.closest(".post-outer")||document;const imgEl=container.querySelector("img.post-thumbnail")||container.querySelector("img");const image=imgEl?imgEl.src:"https://via.placeholder.com/70";wishlist.toggleItem({id,title,url,image})}
if(e.target.closest(".remove-wishlist-item")||e.target.closest(".remove-btn")){const id=e.target.closest("[data-id]").getAttribute("data-id");wishlist.removeItem(id)}
if(e.target.closest(".clear-wishlish")){wishlist.clearAll()}
if(e.target.closest(".view-wishlist")){sessionStorage.setItem("tempWishlistItems",JSON.stringify(wishlist.items));window.location.href="/p/wishlist.html"}});wishlistIcon?.addEventListener("click",(e)=>{e.stopPropagation();if(!window.location.pathname.includes("/p/wishlist.html")){wishlist.openMenu()}});document.querySelectorAll(".close-panel").forEach((btn)=>{btn.addEventListener("click",()=>{wishlistProducts?.classList.remove("active");overlay?.classList.remove("active");document.body.style.position='';document.body.style.top='';document.body.style.width='';window.scrollTo(0,scrollYBeforeOpen)})});overlay?.addEventListener("click",()=>{wishlistProducts?.classList.remove("active");overlay?.classList.remove("active");document.body.style.position='';document.body.style.top='';document.body.style.width='';window.scrollTo(0,scrollYBeforeOpen)});if(window.location.pathname.includes("/p/wishlist.html")){if(wishlistPage)wishlistPage.style.display="block";const tempItems=JSON.parse(sessionStorage.getItem("tempWishlistItems"));if(tempItems){wishlist.items=tempItems;sessionStorage.removeItem("tempWishlistItems");wishlist.save()}
wishlist.updatePageUI()}})
